## Throw

Ключевое слово `throw` выбрасывает исключение. Перехваченное исключение получает то, что было передано после 
`throw`. Чаще всего это new `new Error('some message')`.
Но так же вместо new `Error()` можно передавать любое значение, например свой объект с нужными для обработки ошибок 
функциями.
```javascript
try {
    throw {
        name: 'Custome Error',
        message: 'some message',
        handler: console.log
    };
} catch(err) {
    err.handler(err.message);
}
```
Функция конструктор `Error` возвращает одинаковый результат не зависимо от того как ее вызвали, с ключевым словом `new` 
или без него.
